SWI_SERVICES = {
    'ARG:es': {'country': 'ARG', 'lang': 'es', 'title': 'ARG - Argentina (es)', 'url': 'http://www3.smn.gov.ar/CAP/AR.php', 'hdr_feed': '', 'hdr_atom': ''},
    'AUT:de': {'country': 'AUT', 'lang': 'de', 'title': 'AUT - Austria (de)', 'url': 'http://meteoalarm.eu/ATOM/AT.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'AUT:en': {'country': 'AUT', 'lang': 'de', 'title': 'AUT - Austria (en)', 'url': 'http://meteoalarm.eu/ATOM/AT.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'BRA:pt': {'country': 'BRA', 'lang': 'pt', 'title': 'BRA - Brazil (pt)', 'url': 'http://alert-as.inmet.gov.br/cap_12/rss/alert-as.rss', 'hdr_feed': '', 'hdr_atom': ''},
    'BRB:en': {'country': 'BRB', 'lang': 'en', 'title': 'BRB - Barbados (en)', 'url': 'https://brb-primary.capews.com/capews/pvtbox', 'hdr_feed': '', 'hdr_atom': ''},
    'CAN:en': {'country': 'CAN', 'lang': 'fr', 'title': 'CAN - Canada (en)', 'url': 'http://emergencyalert.alberta.ca/aeapublic/feed.atom', 'hdr_feed': '', 'hdr_atom': ''},
    'CAN:fr': {'country': 'CAN', 'lang': 'fr', 'title': 'CAN - Canada (fr)', 'url': 'http://emergencyalert.alberta.ca/aeapublic/feed.atom', 'hdr_feed': '', 'hdr_atom': ''},
    'CZE:cs': {'country': 'CZE', 'lang': 'cs', 'title': 'CZE - Czech Republic (cs)', 'url': 'http://portal.chmi.cz/files/portal/docs/meteo/om/bulletiny/XOCZ53_OKPR', 'hdr_feed': '', 'hdr_atom': ''},
    'DEU:de': {'country': 'DEU', 'lang': 'de', 'title': 'DEU - Germany (de)', 'url': 'https://www.dwd.de/DWD/warnungen/cap-feed/de/atom.xml', 'hdr_feed': {"User-agent":"Mozilla/5.0/2.19.1 (Linux x86_64)"}, 'hdr_atom': {"User-agent":"Mozilla/5.0/2.19.1 (Linux x86_64)"}},
    'DEU:en': {'country': 'DEU', 'lang': 'de', 'title': 'DEU - Germany (en)', 'url': 'https://www.dwd.de/DWD/warnungen/cap-feed/en/atom.xml', 'hdr_feed': 'User-agent":"Mozilla/5.0/2.19.1 (Linux x86_64)', 'hdr_atom': 'User-agent":"Mozilla/5.0/2.19.1 (Linux x86_64)'},
    'DNK:en': {'country': 'DNK', 'lang': 'en', 'title': 'DNK - Denmark (en)', 'url': 'http://meteoalarm.eu/ATOM/DK.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'ESP:es': {'country': 'ESP', 'lang': 'es', 'title': 'ESP - Spain (es)', 'url': 'http://www.aemet.es/documentos_d/eltiempo/prediccion/avisos/rss/CAP_AFAE_RSS.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'IDN:id': {'country': 'IDN', 'lang': 'id', 'title': 'IDN - Indonesia (id)', 'url': 'https://signature.bmkg.go.id/alert/public/rss.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'KEN:en': {'country': 'KEN', 'lang': 'en', 'title': 'KEN - Kenya (en)', 'url': 'http://www.meteo.go.ke/cap/en/alerts/rss.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'KWT:en': {'country': 'KWT', 'lang': 'en', 'title': 'KWT - Kuwait (en)', 'url': 'http://www.met.gov.kw/rss_eng/kuwait_cap.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'MEX:es': {'country': 'MEX', 'lang': 'es-419', 'title': 'MEX - Mexico (es)', 'url': 'https://correo1.conagua.gob.mx/feedsmn/feedalert.aspx', 'hdr_feed': '', 'hdr_atom': ''},
    'NLD:en': {'country': 'NLD', 'lang': 'pap', 'title': 'NLD - Netherlands (en)', 'url': 'http://201.229.69.218/cap/en/alerts/rss.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'NLD:nl': {'country': 'NLD', 'lang': 'pap', 'title': 'NLD - Netherlands (nl)', 'url': 'http://201.229.69.218/cap/nl/alerts/rss.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'NLD:pap': {'country': 'NLD', 'lang': 'pap', 'title': 'NLD - Netherlands (pap)', 'url': 'http://201.229.69.218/cap/pap/alerts/rss.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'NOR:en': {'country': 'NOR', 'lang': 'en', 'title': 'NOR - Norway (en)', 'url': 'https://alert.met.no/feed?lang=en', 'hdr_feed': '', 'hdr_atom': ''},
    'NOR:nb': {'country': 'NOR', 'lang': 'en', 'title': 'NOR - Norway (nb)', 'url': 'https://alert.met.no/feed?lang=no', 'hdr_feed': '', 'hdr_atom': ''},
    'NOR:no': {'country': 'NOR', 'lang': 'en', 'title': 'NOR - Norway (no)', 'url': 'http://cap.nve.no/', 'hdr_feed': '', 'hdr_atom': ''},
    'NZL:en': {'country': 'NZL', 'lang': 'en', 'title': 'NZL - New Zealand (en)', 'url': 'http://api.geonet.org.nz/cap/1.2/GPA1.0/feed/atom1.0/quake', 'hdr_feed': '', 'hdr_atom': ''},
    'PHL:en': {'country': 'PHL', 'lang': 'en', 'title': 'PHL - Philippines (en)', 'url': 'https://publicalert.pagasa.dost.gov.ph/feeds/', 'hdr_feed': '', 'hdr_atom': ''},
    'ROM:ro': {'country': 'ROM', 'lang': 'ro', 'title': 'ROM - Romania (ro)', 'url': 'http://meteoalarm.eu/ATOM/RO.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'RUS:en': {'country': 'RUS', 'lang': 'en', 'title': 'RUS - Russian Federation (en)', 'url': 'https://meteoinfo.ru/hmc-output/cap/cap-feed/en/atom.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'RUS:ru': {'country': 'RUS', 'lang': 'en', 'title': 'RUS - Russian Federation (ru)', 'url': 'https://meteoinfo.ru/hmc-output/cap/cap-feed/ru/atom.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'THA:th': {'country': 'THA', 'lang': 'th', 'title': 'THA - Thailand (th)', 'url': 'https://www.tmd.go.th/feeds/CAPfeeds.php', 'hdr_feed': '', 'hdr_atom': ''},
    'TZA:en': {'country': 'TZA', 'lang': 'en', 'title': 'TZA - Tanzania, United Republic of (en)', 'url': 'http://tma.meteo.go.tz:8080/feeds/en/alerts/rss.xml', 'hdr_feed': '', 'hdr_atom': ''},
    'USA:en': {'country': 'USA', 'lang': 'en', 'title': 'USA - United States of America (en)', 'url': 'https://alerts.weather.gov/cap/us.php?x=0', 'hdr_feed': {'Accept': 'application/atom+xml'}, 'hdr_atom': {'Accept': 'application/cap+xml'}},
    'ZZZ:zz': {'country': 'ZZ', 'lang': 'zz', 'title': 'Custom configuration', 'url': 'custom', 'hdr_feed': '', 'hdr_atom': ''}
}
